import { Component, OnInit } from '@angular/core';
import {UserService} from '../user.service';
@Component({
  selector: 'app-listvlist',
  templateUrl: './listvlist.component.html',
  styleUrls: ['./listvlist.component.css']
})
export class ListvlistComponent implements OnInit {

/*
  users=[
    {
      "business_id": "FYWN1wneV18bWNgQjJ2GNg",
      "name": "Dental by Design",
      "neighborhood": "4855 E Warner Rd",
      "address": "Ste B9",
      "city": "Ahwatukee",
      "state": "AZ",
      "postal_code": 85044,
      "latitude": 33.3306902,
      "longitude": -111.9785992,
      "stars": 4,
      "review_count": 22,
      "is_open": 1,
      "categories": "Dentists;General Dentistry;Health & Medical;Oral Surgeons;Cosmetic Dentists;Orthodontists"
    },
    {
      "business_id": "He-G7vWjzVUysIKrfNbPUQ",
      "name": "Stephen Szabo Salon",
      "neighborhood": "3101 Washington Rd",
      "address": "McMurray",
      "city": "PA",
      "state": 15317,
      "postal_code": 40.2916853,
      "latitude": -80.1048999,
      "longitude": 3,
      "stars": 11,
      "review_count": 1,
      "is_open": "Hair Stylists;Hair Salons;Men's Hair Salons;Blow Dry/Out Services;Hair Extensions;Beauty & Spas",
      "categories": ""
    },
    {
      "business_id": "KQPW8lFf1y5BT2MxiSZ3QA",
      "name": "Western Motor Vehicle",
      "neighborhood": "6025 N 27th Ave",
      "address": "Ste 1",
      "city": "Phoenix",
      "state": "AZ",
      "postal_code": 85017,
      "latitude": 33.5249025,
      "longitude": -112.1153098,
      "stars": 1.5,
      "review_count": 18,
      "is_open": 1,
      "categories": "Departments of Motor Vehicles;Public Services & Government"
    },
    {
      "business_id": "8DShNS-LuFqpEWIp0HxijA",
      "name": "Sports Authority",
      "neighborhood": "5000 Arizona Mills Cr",
      "address": "Ste 435",
      "city": "Tempe",
      "state": "AZ",
      "postal_code": 85282,
      "latitude": 33.3831468,
      "longitude": -111.9647254,
      "stars": 3,
      "review_count": 9,
      "is_open": 0,
      "categories": "Sporting Goods;Shopping"
    },
    {
      "business_id": "PfOCPjBrlQAnz__NXj9h_w",
      "name": "Brick House Tavern + Tap",
      "neighborhood": "581 Howe Ave",
      "address": "Cuyahoga Falls",
      "city": "OH",
      "state": 44221,
      "postal_code": 41.1195346,
      "latitude": -81.4756898,
      "longitude": 3.5,
      "stars": 116,
      "review_count": 1,
      "is_open": "American (New);Nightlife;Bars;Sandwiches;American (Traditional);Burgers;Restaurants",
      "categories": ""
    },
    {
      "business_id": "o9eMRCWt5PkpLDE0gOPtcQ",
      "name": "Messina",
      "neighborhood": "Richterstr. 11",
      "address": "Stuttgart",
      "city": "BW",
      "state": 70567,
      "postal_code": 48.7272,
      "latitude": 9.14795,
      "longitude": 4,
      "stars": 5,
      "review_count": 1,
      "is_open": "Italian;Restaurants",
      "categories": ""
    },
    {
      "business_id": "kCoE3jvEtg6UVz5SOD3GVw",
      "name": "BDJ Realty",
      "neighborhood": "Summerlin",
      "address": "2620 Regatta Dr",
      "city": "Ste 102",
      "state": "Las Vegas",
      "postal_code": "NV",
      "latitude": 89128,
      "longitude": 36.20743,
      "stars": -115.26846,
      "review_count": 4,
      "is_open": 5,
      "categories": 1
    },
    {
      "business_id": "OD2hnuuTJI9uotcKycxg1A",
      "name": "Soccer Zone",
      "neighborhood": "7240 W Lake Mead Blvd",
      "address": "Ste 4",
      "city": "Las Vegas",
      "state": "NV",
      "postal_code": 89128,
      "latitude": 36.1974844,
      "longitude": -115.2496601,
      "stars": 1.5,
      "review_count": 9,
      "is_open": 1,
      "categories": "Shopping;Sporting Goods"
    },
    {
      "business_id": "EsMcGiZaQuG1OOvL9iUFug",
      "name": "Any Given Sundae",
      "neighborhood": "2612 Brandt School Rd",
      "address": "Wexford",
      "city": "PA",
      "state": 15090,
      "postal_code": 40.6151022445,
      "latitude": -80.0913487465,
      "longitude": 5,
      "stars": 15,
      "review_count": 1,
      "is_open": "Coffee & Tea;Ice Cream & Frozen Yogurt;Food",
      "categories": ""
    },
    {
      "business_id": "TGWhGNusxyMaA4kQVBNeew",
      "name": "Detailing Gone Mobile",
      "neighborhood": "Henderson",
      "address": "NV",
      "city": 89014,
      "state": 36.0558252127,
      "postal_code": -115.04635039,
      "latitude": 5,
      "longitude": 7,
      "stars": 1,
      "review_count": "Automotive;Auto Detailing",
      "is_open": "",
      "categories": ""
    },
    {
      "business_id": "XOSRcvtaKc_Q5H1SAzN20A",
      "name": "East Coast Coffee",
      "neighborhood": "737 West Pike St",
      "address": "Houston",
      "city": "PA",
      "state": 15342,
      "postal_code": 40.2415480142,
      "latitude": -80.2128151059,
      "longitude": 4.5,
      "stars": 3,
      "review_count": 0,
      "is_open": "Breakfast & Brunch;Gluten-Free;Coffee & Tea;Food;Restaurants;Sandwiches",
      "categories": ""
    },
    {
      "business_id": "Y0eMNa5C-YU1RQOZf9XvVA",
      "name": "CubeSmart Self Storage",
      "neighborhood": "2414 South Gilbert Road",
      "address": "Chandler",
      "city": "AZ",
      "state": 85286,
      "postal_code": 33.2717201,
      "latitude": -111.7912569,
      "longitude": 5,
      "stars": 23,
      "review_count": 1,
      "is_open": "Local Services;Self Storage",
      "categories": ""
    },
    {
      "business_id": "xcgFnd-MwkZeO5G2HQ0gAQ",
      "name": "T & T Bakery and Cafe",
      "neighborhood": "Markham Village",
      "address": "35 Main Street N",
      "city": "Markham",
      "state": "ON",
      "postal_code": "L3P 1X3",
      "latitude": 43.8751774,
      "longitude": -79.2601532,
      "stars": 4,
      "review_count": 38,
      "is_open": 1,
      "categories": "Bakeries;Bagels;Food"
    },
    {
      "business_id": "NmZtoE3v8RdSJEczYbMT9g",
      "name": "Complete Dental Care",
      "neighborhood": "107 Whitaker Str",
      "address": "Homestead",
      "city": "PA",
      "state": 15120,
      "postal_code": 40.4014882,
      "latitude": -79.8879161,
      "longitude": 2,
      "stars": 5,
      "review_count": 1,
      "is_open": "General Dentistry;Dentists;Endodontists;Cosmetic Dentists;Health & Medical;Orthodontists",
      "categories": ""
    },
    {
      "business_id": "fNMVV_ZX7CJSDWQGdOM8Nw",
      "name": "Showmars Government Center",
      "neighborhood": "Uptown",
      "address": "600 E 4th St",
      "city": "Charlotte",
      "state": "NC",
      "postal_code": 28202,
      "latitude": 35.2216474,
      "longitude": -80.8393449,
      "stars": 3.5,
      "review_count": 7,
      "is_open": 1,
      "categories": "Restaurants;American (Traditional)"
    },
    {
      "business_id": "l09JfMeQ6ynYs5MCJtrcmQ",
      "name": "Alize Catering",
      "neighborhood": "Yonge and Eglinton",
      "address": "2459 Yonge St",
      "city": "Toronto",
      "state": "ON",
      "postal_code": "M4P 2H6",
      "latitude": 43.7113993,
      "longitude": -79.3993388,
      "stars": 3,
      "review_count": 12,
      "is_open": 0,
      "categories": "Italian;French;Restaurants"
    },
    {
      "business_id": "IQSlT5jGE6CCDhSG0zG3xg",
      "name": "T & Y Nail Spa",
      "neighborhood": "8411 W Thunderbird Rd",
      "address": "Unit 101",
      "city": "Peoria",
      "state": "AZ",
      "postal_code": 85381,
      "latitude": 33.6086538,
      "longitude": -112.2400118,
      "stars": 3,
      "review_count": 20,
      "is_open": 1,
      "categories": "Beauty & Spas;Nail Salons"
    },
    {
      "business_id": "b2I2DXtZVnpUMCXp1JON7A",
      "name": "Meineke Car Care Center",
      "neighborhood": "2518 Ironwood Dr",
      "address": "Sun Prairie",
      "city": "WI",
      "state": 53590,
      "postal_code": 43.18508,
      "latitude": -89.262047,
      "longitude": 3.5,
      "stars": 9,
      "review_count": 1,
      "is_open": "Tires;Oil Change Stations;Auto Repair;Automotive",
      "categories": ""
    },
    {
      "business_id": "0FMKDOU8TJT1x87OKYGDTg",
      "name": "Senior's Barber Shop",
      "neighborhood": "13375 W McDowell",
      "address": "Goodyear",
      "city": "AZ",
      "state": 85395,
      "postal_code": 33.463629,
      "latitude": -112.347038,
      "longitude": 5,
      "stars": 65,
      "review_count": 1,
      "is_open": "Barbers;Beauty & Spas",
      "categories": ""
    },
    {
      "business_id": "Gu-xs3NIQTj3Mj2xYoN2aw",
      "name": "Maxim Bakery & Restaurant",
      "neighborhood": "9665 Bayview Avenue",
      "address": "Unit 1-4",
      "city": "Richmond Hill",
      "state": "ON",
      "postal_code": "L4C 9V4",
      "latitude": 43.8675648,
      "longitude": -79.4126618,
      "stars": 3.5,
      "review_count": 34,
      "is_open": 1,
      "categories": "French;Food;Bakeries;Restaurants"
    },
    {
      "business_id": "lHYiCS-y8AFjUitv6MGpxg",
      "name": "Starbucks",
      "neighborhood": "Liberty Village",
      "address": "85 Hanna Avenue",
      "city": "Toronto",
      "state": "ON",
      "postal_code": "M6K 3S3",
      "latitude": 43.6398633116,
      "longitude": -79.4195331865,
      "stars": 4,
      "review_count": 21,
      "is_open": 1,
      "categories": "Food;Coffee & Tea"
    },
    {
      "business_id": "94KziT6DQ9XlBET3WzIv_w",
      "name": "Fye",
      "neighborhood": "1928 S Gilbert Rd",
      "address": "Mesa",
      "city": "AZ",
      "state": 85204,
      "postal_code": 33.3801334,
      "latitude": -111.7887679,
      "longitude": 4.5,
      "stars": 4,
      "review_count": 0,
      "is_open": "Shopping;Books;Mags;Music & Video;Music & DVDs",
      "categories": ""
    },
    {
      "business_id": "7YIy1tXOor9VCwvaSjuBHg",
      "name": "TSA Checkpoint T-4 A - Phoenix Sky Harbor International Airport",
      "neighborhood": "3400 E Sky Harbor Blvd",
      "address": "Phoenix",
      "city": "AZ",
      "state": 85034,
      "postal_code": 33.4354634,
      "latitude": -112.0069893,
      "longitude": 1.5,
      "stars": 46,
      "review_count": 1,
      "is_open": "Public Services & Government",
      "categories": ""
    },
    {
      "business_id": "PMH4oUa-bWELKogdtkWewg",
      "name": "GoodLife Fitness",
      "neighborhood": "100 City Centre Dr",
      "address": "Mississauga",
      "city": "ON",
      "state": "L5B 2C9",
      "postal_code": 43.5927528,
      "latitude": -79.6430158,
      "longitude": 2,
      "stars": 16,
      "review_count": 1,
      "is_open": "Fitness & Instruction;Sports Clubs;Gyms;Trainers;Active Life",
      "categories": ""
    },
    {
      "business_id": "VSGcuYDV3q-AAZ9ZPq4fBQ",
      "name": "Sportster's",
      "neighborhood": "The Danforth",
      "address": "1430 Danforth Avenue",
      "city": "Toronto",
      "state": "ON",
      "postal_code": "M4J 1N4",
      "latitude": 43.6828673,
      "longitude": -79.3269639,
      "stars": 2.5,
      "review_count": 7,
      "is_open": 1,
      "categories": "Bars;Sports Bars;Nightlife"
    },
    {
      "business_id": "1K4qrnfyzKzGgJPBEcJaNQ",
      "name": "Chula Taberna Mexicana",
      "neighborhood": "Leslieville",
      "address": "1058 Gerrard Street E",
      "city": "Toronto",
      "state": "ON",
      "postal_code": "M4M 3A6",
      "latitude": 43.6692562,
      "longitude": -79.3359022,
      "stars": 3.5,
      "review_count": 39,
      "is_open": 1,
      "categories": "Tiki Bars;Nightlife;Mexican;Restaurants;Bars"
    },
    {
      "business_id": "VBHEsoXQb2AQ76J9l8h1uQ",
      "name": "Alfredo's Jewelry",
      "neighborhood": "Southeast",
      "address": "5775 S Eastern",
      "city": "Ste 103",
      "state": "Las Vegas",
      "postal_code": "NV",
      "latitude": 89119,
      "longitude": 36.0850508374,
      "stars": -115.119420802,
      "review_count": 4.5,
      "is_open": 23,
      "categories": 1
    },
    {
      "business_id": "AtdXq_gu9NTE5rx4ct_dGg",
      "name": "DAVIDsTEA",
      "neighborhood": "Ryerson",
      "address": "10 Dundas Street E",
      "city": "Toronto",
      "state": "ON",
      "postal_code": "M5B 2G9",
      "latitude": 43.6567287,
      "longitude": -79.3807182,
      "stars": 4,
      "review_count": 6,
      "is_open": 1,
      "categories": "Coffee & Tea;Food;Tea Rooms"
    },
    {
      "business_id": "Dj0S-Oe4ytRJzMGUPgYUkw",
      "name": "Panera Bread",
      "neighborhood": "38295 Chestnut Ridge Rd",
      "address": "Elyria",
      "city": "OH",
      "state": 44035,
      "postal_code": 41.343078,
      "latitude": -82.06714,
      "longitude": 2,
      "stars": 4,
      "review_count": 1,
      "is_open": "Soup;Salad;Sandwiches;Restaurants",
      "categories": ""
    },
    {
      "business_id": "gAy4LYpsScrj8POnCW6btQ",
      "name": "Toast Cafe",
      "neighborhood": "2429 Hwy 160 W",
      "address": "Fort Mill",
      "city": "SC",
      "state": 29708,
      "postal_code": 35.0472868,
      "latitude": -80.9905588,
      "longitude": 3.5,
      "stars": 6,
      "review_count": 0,
      "is_open": "Food;American (Traditional);Coffee & Tea;Restaurants",
      "categories": ""
    },
    {
      "business_id": "nbhBRhZtdaZmMMeb2i02pg",
      "name": "Sunnyside Grill",
      "neighborhood": "2777 Steeles Avenue W",
      "address": "Toronto",
      "city": "ON",
      "state": "M3J 3K5",
      "postal_code": 43.7818155,
      "latitude": -79.4904331,
      "longitude": 5,
      "stars": 3,
      "review_count": 1,
      "is_open": "Restaurants;Breakfast & Brunch",
      "categories": ""
    },
    {
      "business_id": "zzMu-6SmqhpvHxVRM6tx9g",
      "name": "Good Brakes Automotive",
      "neighborhood": "12614 N Cave Creek Rd",
      "address": "Ste 104",
      "city": "Phoenix",
      "state": "AZ",
      "postal_code": 85022,
      "latitude": 33.6008771,
      "longitude": -112.0376849,
      "stars": 4,
      "review_count": 5,
      "is_open": 1,
      "categories": "Oil Change Stations;Smog Check Stations;Automotive;Auto Repair"
    },
    {
      "business_id": "1_3nOM7s9WqnJWTNu2-i8Q",
      "name": "Le Bistro Balmoral",
      "neighborhood": "Ville-Marie",
      "address": "305 Rue Sainte-Catherine O",
      "city": "Montreal",
      "state": "QC",
      "postal_code": "H2X 2A1",
      "latitude": 45.5067722126,
      "longitude": -73.5667249688,
      "stars": 3,
      "review_count": 8,
      "is_open": 0,
      "categories": "Arts & Entertainment;Festivals;Restaurants;French;Gastropubs"
    },
    {
      "business_id": "FXHfcFVEfI1vVngW2gVOpw",
      "name": "Bampot House of Tea & Board Games",
      "neighborhood": "201 Harbord Street",
      "address": "Toronto",
      "city": "ON",
      "state": "M5S 1H6",
      "postal_code": 43.6615816807,
      "latitude": -79.4088784561,
      "longitude": 4,
      "stars": 55,
      "review_count": 1,
      "is_open": "Coffee & Tea;Restaurants;Food;Mediterranean;Tea Rooms",
      "categories": ""
    },
    {
      "business_id": "7gquCdaFoHZCcLYDttpHtw",
      "name": "Bubbly Nails",
      "neighborhood": "8439 Charlotte Hwy",
      "address": "Fort Mill",
      "city": "SC",
      "state": 29707,
      "postal_code": 34.9570617825,
      "latitude": -80.8539120108,
      "longitude": 4,
      "stars": 17,
      "review_count": 1,
      "is_open": "Nail Salons;Beauty & Spas",
      "categories": ""
    },
    {
      "business_id": "8y56fOiKhtCnqaiYB2S2Qg",
      "name": "Brewster's Pub",
      "neighborhood": "96 S Main St",
      "address": "Munroe Falls",
      "city": "OH",
      "state": 44308,
      "postal_code": 41.136622,
      "latitude": -81.4392592,
      "longitude": 4,
      "stars": 4,
      "review_count": 1,
      "is_open": "Nightlife;Pubs;Bars",
      "categories": ""
    },
    {
      "business_id": "ok38fApaT1TBEU-IH85BvA",
      "name": "Kool Pool Care & Repair",
      "neighborhood": "3245 W Florimond Rd",
      "address": "Phoenix",
      "city": "AZ",
      "state": 85086,
      "postal_code": 33.8039,
      "latitude": -112.130405,
      "longitude": 5,
      "stars": 5,
      "review_count": 1,
      "is_open": "Home Services;Contractors;Pool & Hot Tub Service;Pool Cleaners",
      "categories": ""
    },
    {
      "business_id": "lj0MiK5_fyv9df2twnsI7g",
      "name": "Pampered Hair Passionate about Hair",
      "neighborhood": "Anthem",
      "address": "2470 Paseo Verde Pkwy",
      "city": "Henderson",
      "state": "NV",
      "postal_code": 89074,
      "latitude": 36.0194946,
      "longitude": -115.0947223,
      "stars": 5,
      "review_count": 3,
      "is_open": 1,
      "categories": "Hair Salons;Blow Dry/Out Services;Hair Stylists;Beauty & Spas;Hair Extensions"
    },
    {
      "business_id": "S4a42azhoOmr0fpeNkggHg",
      "name": "By Design",
      "neighborhood": "11812 Carolina Place Pkwy",
      "address": "Ste C",
      "city": "Pineville",
      "state": "NC",
      "postal_code": 28134,
      "latitude": 35.0735981,
      "longitude": -80.8815165,
      "stars": 2.5,
      "review_count": 3,
      "is_open": 0,
      "categories": "Home & Garden;Furniture Stores;Shopping"
    },
    {
      "business_id": "A_Ij4SwFmlRbVtRnsdSzWA",
      "name": "Ciao Baby Catering",
      "neighborhood": "15041 N Airport Dr",
      "address": "Scottsdale",
      "city": "AZ",
      "state": 85260,
      "postal_code": 33.6218351,
      "latitude": -111.9155977,
      "longitude": 2,
      "stars": 5,
      "review_count": 0,
      "is_open": "Event Planning & Services;Caterers",
      "categories": ""
    },
    {
      "business_id": "tRVx2c89coruPRwYhGTcTw",
      "name": "Yuzu",
      "neighborhood": "13603 Madison Ave",
      "address": "Lakewood",
      "city": "OH",
      "state": 44107,
      "postal_code": 41.4768463,
      "latitude": -81.7869709,
      "longitude": 3.5,
      "stars": 78,
      "review_count": 1,
      "is_open": "Nightlife;Izakaya;Comfort Food;Cocktail Bars;Asian Fusion;Bars;Japanese;Restaurants;Gastropubs;Tapas/Small Plates",
      "categories": ""
    },
    {
      "business_id": "1Jp_hmPNUZArNqzpbm7B0g",
      "name": "Task Electric",
      "neighborhood": "Spring Valley",
      "address": "7260 Cimarron Rd",
      "city": "Ste 130",
      "state": "Las Vegas",
      "postal_code": "NV",
      "latitude": 89113,
      "longitude": 36.056382,
      "stars": -115.269332,
      "review_count": 4.5,
      "is_open": 20,
      "categories": 1
    },
    {
      "business_id": "zjySmTfL9WiMDVgp8-Jp3w",
      "name": "TCBY",
      "neighborhood": "610 Jetton St",
      "address": "Ste 130",
      "city": "Davidson",
      "state": "NC",
      "postal_code": 28036,
      "latitude": 35.5012273,
      "longitude": -80.8609494,
      "stars": 3.5,
      "review_count": 3,
      "is_open": 1,
      "categories": "Desserts;Ice Cream & Frozen Yogurt;Food"
    },
    {
      "business_id": "5qpi5VQ_S2Itm8xvRm1k8Q",
      "name": "Olsen Firearms",
      "neighborhood": "28212 N Tatum Blvd",
      "address": "Ste D4",
      "city": "Cave Creek",
      "state": "AZ",
      "postal_code": 85331,
      "latitude": 33.7416293,
      "longitude": -111.9809164,
      "stars": 5,
      "review_count": 9,
      "is_open": 1,
      "categories": "Shopping;Guns & Ammo"
    },
    {
      "business_id": "BnuzcebyB1AfxH0kjNWqSg",
      "name": "Carrabba's Italian Grill",
      "neighborhood": "245 Lancaster Ave",
      "address": "Frazer",
      "city": "PA",
      "state": 19355,
      "postal_code": 40.0410025289,
      "latitude": -75.5424965117,
      "longitude": 3.5,
      "stars": 25,
      "review_count": 0,
      "is_open": "Restaurants;Italian;Seafood",
      "categories": ""
    },
    {
      "business_id": "rDMptJYWtnMhpQu_rRXHng",
      "name": "McDonald's",
      "neighborhood": "719 E Thunderbird Rd",
      "address": "Phoenix",
      "city": "AZ",
      "state": 85022,
      "postal_code": 33.6070702,
      "latitude": -112.0643825,
      "longitude": 1,
      "stars": 10,
      "review_count": 1,
      "is_open": "Fast Food;Burgers;Restaurants",
      "categories": ""
    },
    {
      "business_id": "1WBkAuQg81kokZIPMpn9Zg",
      "name": "Charr An American Burger Bar",
      "neighborhood": "777 E Thunderbird Rd",
      "address": "Ste 107",
      "city": "Phoenix",
      "state": "AZ",
      "postal_code": 85022,
      "latitude": 33.60731,
      "longitude": -112.063404,
      "stars": 3,
      "review_count": 232,
      "is_open": 1,
      "categories": "Burgers;Restaurants"
    },
    {
      "business_id": "Z-4KHBDbdwyC7PwA_JE5Xw",
      "name": "William Jon Salon & Spa",
      "neighborhood": "Regent",
      "address": "2701 University Ave",
      "city": "Ste H",
      "state": "Madison",
      "postal_code": "WI",
      "latitude": 53705,
      "longitude": 43.0731452,
      "stars": -89.4344018,
      "review_count": 4.5,
      "is_open": 14,
      "categories": 1
    },
    {
      "business_id": "DPQnTnNw2PJj7DdENM98Cw",
      "name": "Star Nursery",
      "neighborhood": "5340 Boulder Hwy",
      "address": "Las Vegas",
      "city": "NV",
      "state": 89122,
      "postal_code": 36.105196,
      "latitude": -115.0568796,
      "longitude": 3.5,
      "stars": 25,
      "review_count": 1,
      "is_open": "Nurseries & Gardening;Home & Garden;Shopping",
      "categories": ""
    },
    {
      "business_id": "_F3AMoo_zdl-he384ISQbw",
      "name": "Rock of Ages",
      "neighborhood": "3700 W Flamingo Rd",
      "address": "Las Vegas",
      "city": "NV",
      "state": 89109,
      "postal_code": 36.1169648,
      "latitude": -115.185696,
      "longitude": 4,
      "stars": 213,
      "review_count": 1,
      "is_open": "Arts & Entertainment;Performing Arts",
      "categories": ""
    },
    {
      "business_id": "-ooEO2YqDQVYNHnSF2BPfw",
      "name": "Restaurant Lucca",
      "neighborhood": "Rosemont-La Petite-Patrie",
      "address": "12 Rue Dante",
      "city": "Montréal",
      "state": "QC",
      "postal_code": "H2S 1J5",
      "latitude": 45.5328965,
      "longitude": -73.6136037,
      "stars": 4.5,
      "review_count": 11,
      "is_open": 1,
      "categories": "Italian;Restaurants"
    },
    {
      "business_id": "FmGZh8ZwEnSO860_2eiYHw",
      "name": "Enterprise Rent-A-Car",
      "neighborhood": "Homestead",
      "address": "908 E 8th Ave",
      "city": "Homestead",
      "state": "PA",
      "postal_code": 15120,
      "latitude": 40.409116,
      "longitude": -79.897415,
      "stars": 3,
      "review_count": 4,
      "is_open": 1,
      "categories": "Hotels & Travel;Car Rental"
    },
    {
      "business_id": "Pd52CjgyEU3Rb8co6QfTPw",
      "name": "Flight Deck Bar & Grill",
      "neighborhood": "Southeast",
      "address": "6730 S Las Vegas Blvd",
      "city": "Las Vegas",
      "state": "NV",
      "postal_code": 89119,
      "latitude": 36.0669136,
      "longitude": -115.1708484,
      "stars": 4,
      "review_count": 13,
      "is_open": 1,
      "categories": "Nightlife;Bars;Barbeque;Sports Bars;American (New);Restaurants"
    },
    {
      "business_id": "4srfPk1s8nlm1YusyDUbjg",
      "name": "Subway",
      "neighborhood": "Southeast",
      "address": "6889 S Eastern Ave",
      "city": "Ste 101",
      "state": "Las Vegas",
      "postal_code": "NV",
      "latitude": 89119,
      "longitude": 36.0646523,
      "stars": -115.1189541,
      "review_count": 2.5,
      "is_open": 6,
      "categories": 1
    },
    {
      "business_id": "n7V4cD-KqqE3OXk0irJTyA",
      "name": "GameWorks",
      "neighborhood": "Southeast",
      "address": "6587 Las Vegas Blvd S",
      "city": "Ste 171",
      "state": "Las Vegas",
      "postal_code": "NV",
      "latitude": 89119,
      "longitude": 36.0682585154,
      "stars": -115.1788768,
      "review_count": 3,
      "is_open": 349,
      "categories": 1
    },
    {
      "business_id": "c_XbaJqhm-5ycSBOkVUBmg",
      "name": "Don Taco",
      "neighborhood": "Ville-Marie",
      "address": "1855 Rue Saint Catherine Ouest",
      "city": "H3H 1M2",
      "state": "Montreal",
      "postal_code": "QC",
      "latitude": "H3H 1M2",
      "longitude": 45.4932164,
      "stars": -73.5803794,
      "review_count": 3.5,
      "is_open": 33,
      "categories": 1
    },
    {
      "business_id": "ykJM7EuGziATZ5u2qIT08g",
      "name": "My Fitness World",
      "neighborhood": "South End",
      "address": "1225 S Church St",
      "city": "Ste B",
      "state": "Charlotte",
      "postal_code": "NC",
      "latitude": 28203,
      "longitude": 35.220211,
      "stars": -80.855785,
      "review_count": 5,
      "is_open": 4,
      "categories": 1
    }];
    */
    users =[];
    constructor(private userService: UserService){}
    ngOnInit(){
      this.userService.getUsers()
      .subscribe(data =>{
        this.users =data;
      });
    }
    key:string='default'; //set default
    reverse:boolean=false;
    sort(key){
      this.key=key;
      this.reverse=!this.reverse;
    }
    //initializing p to one
    p:number=1;
}
