import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  students=[{"name":"ash"},{"name":"arti"}];
   users=[
    {
      "business_id": "FYWN1wneV18bWNgQjJ2GNg",
      "name": "Dental by Design",
      "neighborhood": "4855 E Warner Rd",
      "address": "Ste B9",
      "city": "Ahwatukee",
      "state": "AZ",
      "postal_code": 85044,
      "latitude": 33.3306902,
      "longitude": -111.9785992,
      "stars": 4,
      "review_count": 22,
      "is_open": 1,
      "categories": "Dentists;General Dentistry;Health & Medical;Oral Surgeons;Cosmetic Dentists;Orthodontists"
    },
    {
      "business_id": "He-G7vWjzVUysIKrfNbPUQ",
      "name": "Stephen Szabo Salon",
      "neighborhood": "3101 Washington Rd",
      "address": "McMurray",
      "city": "PA",
      "state": 15317,
      "postal_code": 40.2916853,
      "latitude": -80.1048999,
      "longitude": 3,
      "stars": 11,
      "review_count": 1,
      "is_open": "Hair Stylists;Hair Salons;Men's Hair Salons;Blow Dry/Out Services;Hair Extensions;Beauty & Spas",
      "categories": ""
    },
    {
      "business_id": "KQPW8lFf1y5BT2MxiSZ3QA",
      "name": "Western Motor Vehicle",
      "neighborhood": "6025 N 27th Ave",
      "address": "Ste 1",
      "city": "Phoenix",
      "state": "AZ",
      "postal_code": 85017,
      "latitude": 33.5249025,
      "longitude": -112.1153098,
      "stars": 1.5,
      "review_count": 18,
      "is_open": 1,
      "categories": "Departments of Motor Vehicles;Public Services & Government"
    },
    {
      "business_id": "8DShNS-LuFqpEWIp0HxijA",
      "name": "Sports Authority",
      "neighborhood": "5000 Arizona Mills Cr",
      "address": "Ste 435",
      "city": "Tempe",
      "state": "AZ",
      "postal_code": 85282,
      "latitude": 33.3831468,
      "longitude": -111.9647254,
      "stars": 3,
      "review_count": 9,
      "is_open": 0,
      "categories": "Sporting Goods;Shopping"
    },
    {
      "business_id": "PfOCPjBrlQAnz__NXj9h_w",
      "name": "Brick House Tavern + Tap",
      "neighborhood": "581 Howe Ave",
      "address": "Cuyahoga Falls",
      "city": "OH",
      "state": 44221,
      "postal_code": 41.1195346,
      "latitude": -81.4756898,
      "longitude": 3.5,
      "stars": 116,
      "review_count": 1,
      "is_open": "American (New);Nightlife;Bars;Sandwiches;American (Traditional);Burgers;Restaurants",
      "categories": ""
    },
    {
      "business_id": "o9eMRCWt5PkpLDE0gOPtcQ",
      "name": "Messina",
      "neighborhood": "Richterstr. 11",
      "address": "Stuttgart",
      "city": "BW",
      "state": 70567,
      "postal_code": 48.7272,
      "latitude": 9.14795,
      "longitude": 4,
      "stars": 5,
      "review_count": 1,
      "is_open": "Italian;Restaurants",
      "categories": ""
    },
    {
      "business_id": "kCoE3jvEtg6UVz5SOD3GVw",
      "name": "BDJ Realty",
      "neighborhood": "Summerlin",
      "address": "2620 Regatta Dr",
      "city": "Ste 102",
      "state": "Las Vegas",
      "postal_code": "NV",
      "latitude": 89128,
      "longitude": 36.20743,
      "stars": -115.26846,
      "review_count": 4,
      "is_open": 5,
      "categories": 1
    },
    {
      "business_id": "OD2hnuuTJI9uotcKycxg1A",
      "name": "Soccer Zone",
      "neighborhood": "7240 W Lake Mead Blvd",
      "address": "Ste 4",
      "city": "Las Vegas",
      "state": "NV",
      "postal_code": 89128,
      "latitude": 36.1974844,
      "longitude": -115.2496601,
      "stars": 1.5,
      "review_count": 9,
      "is_open": 1,
      "categories": "Shopping;Sporting Goods"
    },
    {
      "business_id": "EsMcGiZaQuG1OOvL9iUFug",
      "name": "Any Given Sundae",
      "neighborhood": "2612 Brandt School Rd",
      "address": "Wexford",
      "city": "PA",
      "state": 15090,
      "postal_code": 40.6151022445,
      "latitude": -80.0913487465,
      "longitude": 5,
      "stars": 15,
      "review_count": 1,
      "is_open": "Coffee & Tea;Ice Cream & Frozen Yogurt;Food",
      "categories": ""
    },
    {
      "business_id": "TGWhGNusxyMaA4kQVBNeew",
      "name": "Detailing Gone Mobile",
      "neighborhood": "Henderson",
      "address": "NV",
      "city": 89014,
      "state": 36.0558252127,
      "postal_code": -115.04635039,
      "latitude": 5,
      "longitude": 7,
      "stars": 1,
      "review_count": "Automotive;Auto Detailing",
      "is_open": "",
      "categories": ""
    },
    {
      "business_id": "XOSRcvtaKc_Q5H1SAzN20A",
      "name": "East Coast Coffee",
      "neighborhood": "737 West Pike St",
      "address": "Houston",
      "city": "PA",
      "state": 15342,
      "postal_code": 40.2415480142,
      "latitude": -80.2128151059,
      "longitude": 4.5,
      "stars": 3,
      "review_count": 0,
      "is_open": "Breakfast & Brunch;Gluten-Free;Coffee & Tea;Food;Restaurants;Sandwiches",
      "categories": ""
    },
    {
      "business_id": "Y0eMNa5C-YU1RQOZf9XvVA",
      "name": "CubeSmart Self Storage",
      "neighborhood": "2414 South Gilbert Road",
      "address": "Chandler",
      "city": "AZ",
      "state": 85286,
      "postal_code": 33.2717201,
      "latitude": -111.7912569,
      "longitude": 5,
      "stars": 23,
      "review_count": 1,
      "is_open": "Local Services;Self Storage",
      "categories": ""
    },
    {
      "business_id": "xcgFnd-MwkZeO5G2HQ0gAQ",
      "name": "T & T Bakery and Cafe",
      "neighborhood": "Markham Village",
      "address": "35 Main Street N",
      "city": "Markham",
      "state": "ON",
      "postal_code": "L3P 1X3",
      "latitude": 43.8751774,
      "longitude": -79.2601532,
      "stars": 4,
      "review_count": 38,
      "is_open": 1,
      "categories": "Bakeries;Bagels;Food"
    },
    {
      "business_id": "NmZtoE3v8RdSJEczYbMT9g",
      "name": "Complete Dental Care",
      "neighborhood": "107 Whitaker Str",
      "address": "Homestead",
      "city": "PA",
      "state": 15120,
      "postal_code": 40.4014882,
      "latitude": -79.8879161,
      "longitude": 2,
      "stars": 5,
      "review_count": 1,
      "is_open": "General Dentistry;Dentists;Endodontists;Cosmetic Dentists;Health & Medical;Orthodontists",
      "categories": ""
    },
    {
      "business_id": "fNMVV_ZX7CJSDWQGdOM8Nw",
      "name": "Showmars Government Center",
      "neighborhood": "Uptown",
      "address": "600 E 4th St",
      "city": "Charlotte",
      "state": "NC",
      "postal_code": 28202,
      "latitude": 35.2216474,
      "longitude": -80.8393449,
      "stars": 3.5,
      "review_count": 7,
      "is_open": 1,
      "categories": "Restaurants;American (Traditional)"
    },
    {
      "business_id": "l09JfMeQ6ynYs5MCJtrcmQ",
      "name": "Alize Catering",
      "neighborhood": "Yonge and Eglinton",
      "address": "2459 Yonge St",
      "city": "Toronto",
      "state": "ON",
      "postal_code": "M4P 2H6",
      "latitude": 43.7113993,
      "longitude": -79.3993388,
      "stars": 3,
      "review_count": 12,
      "is_open": 0,
      "categories": "Italian;French;Restaurants"
    },
    {
      "business_id": "IQSlT5jGE6CCDhSG0zG3xg",
      "name": "T & Y Nail Spa",
      "neighborhood": "8411 W Thunderbird Rd",
      "address": "Unit 101",
      "city": "Peoria",
      "state": "AZ",
      "postal_code": 85381,
      "latitude": 33.6086538,
      "longitude": -112.2400118,
      "stars": 3,
      "review_count": 20,
      "is_open": 1,
      "categories": "Beauty & Spas;Nail Salons"
    },
    {
      "business_id": "b2I2DXtZVnpUMCXp1JON7A",
      "name": "Meineke Car Care Center",
      "neighborhood": "2518 Ironwood Dr",
      "address": "Sun Prairie",
      "city": "WI",
      "state": 53590,
      "postal_code": 43.18508,
      "latitude": -89.262047,
      "longitude": 3.5,
      "stars": 9,
      "review_count": 1,
      "is_open": "Tires;Oil Change Stations;Auto Repair;Automotive",
      "categories": ""
    },
    {
      "business_id": "0FMKDOU8TJT1x87OKYGDTg",
      "name": "Senior's Barber Shop",
      "neighborhood": "13375 W McDowell",
      "address": "Goodyear",
      "city": "AZ",
      "state": 85395,
      "postal_code": 33.463629,
      "latitude": -112.347038,
      "longitude": 5,
      "stars": 65,
      "review_count": 1,
      "is_open": "Barbers;Beauty & Spas",
      "categories": ""
    },
    {
      "business_id": "Gu-xs3NIQTj3Mj2xYoN2aw",
      "name": "Maxim Bakery & Restaurant",
      "neighborhood": "9665 Bayview Avenue",
      "address": "Unit 1-4",
      "city": "Richmond Hill",
      "state": "ON",
      "postal_code": "L4C 9V4",
      "latitude": 43.8675648,
      "longitude": -79.4126618,
      "stars": 3.5,
      "review_count": 34,
      "is_open": 1,
      "categories": "French;Food;Bakeries;Restaurants"
    },
    {
      "business_id": "lHYiCS-y8AFjUitv6MGpxg",
      "name": "Starbucks",
      "neighborhood": "Liberty Village",
      "address": "85 Hanna Avenue",
      "city": "Toronto",
      "state": "ON",
      "postal_code": "M6K 3S3",
      "latitude": 43.6398633116,
      "longitude": -79.4195331865,
      "stars": 4,
      "review_count": 21,
      "is_open": 1,
      "categories": "Food;Coffee & Tea"
    },
    {
      "business_id": "94KziT6DQ9XlBET3WzIv_w",
      "name": "Fye",
      "neighborhood": "1928 S Gilbert Rd",
      "address": "Mesa",
      "city": "AZ",
      "state": 85204,
      "postal_code": 33.3801334,
      "latitude": -111.7887679,
      "longitude": 4.5,
      "stars": 4,
      "review_count": 0,
      "is_open": "Shopping;Books;Mags;Music & Video;Music & DVDs",
      "categories": ""
    },
    {
      "business_id": "7YIy1tXOor9VCwvaSjuBHg",
      "name": "TSA Checkpoint T-4 A - Phoenix Sky Harbor International Airport",
      "neighborhood": "3400 E Sky Harbor Blvd",
      "address": "Phoenix",
      "city": "AZ",
      "state": 85034,
      "postal_code": 33.4354634,
      "latitude": -112.0069893,
      "longitude": 1.5,
      "stars": 46,
      "review_count": 1,
      "is_open": "Public Services & Government",
      "categories": ""
    },
    {
      "business_id": "PMH4oUa-bWELKogdtkWewg",
      "name": "GoodLife Fitness",
      "neighborhood": "100 City Centre Dr",
      "address": "Mississauga",
      "city": "ON",
      "state": "L5B 2C9",
      "postal_code": 43.5927528,
      "latitude": -79.6430158,
      "longitude": 2,
      "stars": 16,
      "review_count": 1,
      "is_open": "Fitness & Instruction;Sports Clubs;Gyms;Trainers;Active Life",
      "categories": ""
    },
    {
      "business_id": "VSGcuYDV3q-AAZ9ZPq4fBQ",
      "name": "Sportster's",
      "neighborhood": "The Danforth",
      "address": "1430 Danforth Avenue",
      "city": "Toronto",
      "state": "ON",
      "postal_code": "M4J 1N4",
      "latitude": 43.6828673,
      "longitude": -79.3269639,
      "stars": 2.5,
      "review_count": 7,
      "is_open": 1,
      "categories": "Bars;Sports Bars;Nightlife"
    },
    {
      "business_id": "1K4qrnfyzKzGgJPBEcJaNQ",
      "name": "Chula Taberna Mexicana",
      "neighborhood": "Leslieville",
      "address": "1058 Gerrard Street E",
      "city": "Toronto",
      "state": "ON",
      "postal_code": "M4M 3A6",
      "latitude": 43.6692562,
      "longitude": -79.3359022,
      "stars": 3.5,
      "review_count": 39,
      "is_open": 1,
      "categories": "Tiki Bars;Nightlife;Mexican;Restaurants;Bars"
    },
    {
      "business_id": "VBHEsoXQb2AQ76J9l8h1uQ",
      "name": "Alfredo's Jewelry",
      "neighborhood": "Southeast",
      "address": "5775 S Eastern",
      "city": "Ste 103",
      "state": "Las Vegas",
      "postal_code": "NV",
      "latitude": 89119,
      "longitude": 36.0850508374,
      "stars": -115.119420802,
      "review_count": 4.5,
      "is_open": 23,
      "categories": 1
    },
    {
      "business_id": "AtdXq_gu9NTE5rx4ct_dGg",
      "name": "DAVIDsTEA",
      "neighborhood": "Ryerson",
      "address": "10 Dundas Street E",
      "city": "Toronto",
      "state": "ON",
      "postal_code": "M5B 2G9",
      "latitude": 43.6567287,
      "longitude": -79.3807182,
      "stars": 4,
      "review_count": 6,
      "is_open": 1,
      "categories": "Coffee & Tea;Food;Tea Rooms"
    },
    {
      "business_id": "Dj0S-Oe4ytRJzMGUPgYUkw",
      "name": "Panera Bread",
      "neighborhood": "38295 Chestnut Ridge Rd",
      "address": "Elyria",
      "city": "OH",
      "state": 44035,
      "postal_code": 41.343078,
      "latitude": -82.06714,
      "longitude": 2,
      "stars": 4,
      "review_count": 1,
      "is_open": "Soup;Salad;Sandwiches;Restaurants",
      "categories": ""
    },
    {
      "business_id": "gAy4LYpsScrj8POnCW6btQ",
      "name": "Toast Cafe",
      "neighborhood": "2429 Hwy 160 W",
      "address": "Fort Mill",
      "city": "SC",
      "state": 29708,
      "postal_code": 35.0472868,
      "latitude": -80.9905588,
      "longitude": 3.5,
      "stars": 6,
      "review_count": 0,
      "is_open": "Food;American (Traditional);Coffee & Tea;Restaurants",
      "categories": ""
    },
    {
      "business_id": "nbhBRhZtdaZmMMeb2i02pg",
      "name": "Sunnyside Grill",
      "neighborhood": "2777 Steeles Avenue W",
      "address": "Toronto",
      "city": "ON",
      "state": "M3J 3K5",
      "postal_code": 43.7818155,
      "latitude": -79.4904331,
      "longitude": 5,
      "stars": 3,
      "review_count": 1,
      "is_open": "Restaurants;Breakfast & Brunch",
      "categories": ""
    },
    {
      "business_id": "zzMu-6SmqhpvHxVRM6tx9g",
      "name": "Good Brakes Automotive",
      "neighborhood": "12614 N Cave Creek Rd",
      "address": "Ste 104",
      "city": "Phoenix",
      "state": "AZ",
      "postal_code": 85022,
      "latitude": 33.6008771,
      "longitude": -112.0376849,
      "stars": 4,
      "review_count": 5,
      "is_open": 1,
      "categories": "Oil Change Stations;Smog Check Stations;Automotive;Auto Repair"
    },
    {
      "business_id": "1_3nOM7s9WqnJWTNu2-i8Q",
      "name": "Le Bistro Balmoral",
      "neighborhood": "Ville-Marie",
      "address": "305 Rue Sainte-Catherine O",
      "city": "Montreal",
      "state": "QC",
      "postal_code": "H2X 2A1",
      "latitude": 45.5067722126,
      "longitude": -73.5667249688,
      "stars": 3,
      "review_count": 8,
      "is_open": 0,
      "categories": "Arts & Entertainment;Festivals;Restaurants;French;Gastropubs"
    },
    {
      "business_id": "FXHfcFVEfI1vVngW2gVOpw",
      "name": "Bampot House of Tea & Board Games",
      "neighborhood": "201 Harbord Street",
      "address": "Toronto",
      "city": "ON",
      "state": "M5S 1H6",
      "postal_code": 43.6615816807,
      "latitude": -79.4088784561,
      "longitude": 4,
      "stars": 55,
      "review_count": 1,
      "is_open": "Coffee & Tea;Restaurants;Food;Mediterranean;Tea Rooms",
      "categories": ""
    },
    {
      "business_id": "7gquCdaFoHZCcLYDttpHtw",
      "name": "Bubbly Nails",
      "neighborhood": "8439 Charlotte Hwy",
      "address": "Fort Mill",
      "city": "SC",
      "state": 29707,
      "postal_code": 34.9570617825,
      "latitude": -80.8539120108,
      "longitude": 4,
      "stars": 17,
      "review_count": 1,
      "is_open": "Nail Salons;Beauty & Spas",
      "categories": ""
    },
    {
      "business_id": "8y56fOiKhtCnqaiYB2S2Qg",
      "name": "Brewster's Pub",
      "neighborhood": "96 S Main St",
      "address": "Munroe Falls",
      "city": "OH",
      "state": 44308,
      "postal_code": 41.136622,
      "latitude": -81.4392592,
      "longitude": 4,
      "stars": 4,
      "review_count": 1,
      "is_open": "Nightlife;Pubs;Bars",
      "categories": ""
    },
    {
      "business_id": "ok38fApaT1TBEU-IH85BvA",
      "name": "Kool Pool Care & Repair",
      "neighborhood": "3245 W Florimond Rd",
      "address": "Phoenix",
      "city": "AZ",
      "state": 85086,
      "postal_code": 33.8039,
      "latitude": -112.130405,
      "longitude": 5,
      "stars": 5,
      "review_count": 1,
      "is_open": "Home Services;Contractors;Pool & Hot Tub Service;Pool Cleaners",
      "categories": ""
    },
    {
      "business_id": "lj0MiK5_fyv9df2twnsI7g",
      "name": "Pampered Hair Passionate about Hair",
      "neighborhood": "Anthem",
      "address": "2470 Paseo Verde Pkwy",
      "city": "Henderson",
      "state": "NV",
      "postal_code": 89074,
      "latitude": 36.0194946,
      "longitude": -115.0947223,
      "stars": 5,
      "review_count": 3,
      "is_open": 1,
      "categories": "Hair Salons;Blow Dry/Out Services;Hair Stylists;Beauty & Spas;Hair Extensions"
    },
    {
      "business_id": "S4a42azhoOmr0fpeNkggHg",
      "name": "By Design",
      "neighborhood": "11812 Carolina Place Pkwy",
      "address": "Ste C",
      "city": "Pineville",
      "state": "NC",
      "postal_code": 28134,
      "latitude": 35.0735981,
      "longitude": -80.8815165,
      "stars": 2.5,
      "review_count": 3,
      "is_open": 0,
      "categories": "Home & Garden;Furniture Stores;Shopping"
    },
    {
      "business_id": "A_Ij4SwFmlRbVtRnsdSzWA",
      "name": "Ciao Baby Catering",
      "neighborhood": "15041 N Airport Dr",
      "address": "Scottsdale",
      "city": "AZ",
      "state": 85260,
      "postal_code": 33.6218351,
      "latitude": -111.9155977,
      "longitude": 2,
      "stars": 5,
      "review_count": 0,
      "is_open": "Event Planning & Services;Caterers",
      "categories": ""
    },
    {
      "business_id": "tRVx2c89coruPRwYhGTcTw",
      "name": "Yuzu",
      "neighborhood": "13603 Madison Ave",
      "address": "Lakewood",
      "city": "OH",
      "state": 44107,
      "postal_code": 41.4768463,
      "latitude": -81.7869709,
      "longitude": 3.5,
      "stars": 78,
      "review_count": 1,
      "is_open": "Nightlife;Izakaya;Comfort Food;Cocktail Bars;Asian Fusion;Bars;Japanese;Restaurants;Gastropubs;Tapas/Small Plates",
      "categories": ""
    },
    {
      "business_id": "1Jp_hmPNUZArNqzpbm7B0g",
      "name": "Task Electric",
      "neighborhood": "Spring Valley",
      "address": "7260 Cimarron Rd",
      "city": "Ste 130",
      "state": "Las Vegas",
      "postal_code": "NV",
      "latitude": 89113,
      "longitude": 36.056382,
      "stars": -115.269332,
      "review_count": 4.5,
      "is_open": 20,
      "categories": 1
    },
    {
      "business_id": "zjySmTfL9WiMDVgp8-Jp3w",
      "name": "TCBY",
      "neighborhood": "610 Jetton St",
      "address": "Ste 130",
      "city": "Davidson",
      "state": "NC",
      "postal_code": 28036,
      "latitude": 35.5012273,
      "longitude": -80.8609494,
      "stars": 3.5,
      "review_count": 3,
      "is_open": 1,
      "categories": "Desserts;Ice Cream & Frozen Yogurt;Food"
    },
    {
      "business_id": "5qpi5VQ_S2Itm8xvRm1k8Q",
      "name": "Olsen Firearms",
      "neighborhood": "28212 N Tatum Blvd",
      "address": "Ste D4",
      "city": "Cave Creek",
      "state": "AZ",
      "postal_code": 85331,
      "latitude": 33.7416293,
      "longitude": -111.9809164,
      "stars": 5,
      "review_count": 9,
      "is_open": 1,
      "categories": "Shopping;Guns & Ammo"
    },
    {
      "business_id": "BnuzcebyB1AfxH0kjNWqSg",
      "name": "Carrabba's Italian Grill",
      "neighborhood": "245 Lancaster Ave",
      "address": "Frazer",
      "city": "PA",
      "state": 19355,
      "postal_code": 40.0410025289,
      "latitude": -75.5424965117,
      "longitude": 3.5,
      "stars": 25,
      "review_count": 0,
      "is_open": "Restaurants;Italian;Seafood",
      "categories": ""
    },
    {
      "business_id": "rDMptJYWtnMhpQu_rRXHng",
      "name": "McDonald's",
      "neighborhood": "719 E Thunderbird Rd",
      "address": "Phoenix",
      "city": "AZ",
      "state": 85022,
      "postal_code": 33.6070702,
      "latitude": -112.0643825,
      "longitude": 1,
      "stars": 10,
      "review_count": 1,
      "is_open": "Fast Food;Burgers;Restaurants",
      "categories": ""
    },
    {
      "business_id": "1WBkAuQg81kokZIPMpn9Zg",
      "name": "Charr An American Burger Bar",
      "neighborhood": "777 E Thunderbird Rd",
      "address": "Ste 107",
      "city": "Phoenix",
      "state": "AZ",
      "postal_code": 85022,
      "latitude": 33.60731,
      "longitude": -112.063404,
      "stars": 3,
      "review_count": 232,
      "is_open": 1,
      "categories": "Burgers;Restaurants"
    },
    {
      "business_id": "Z-4KHBDbdwyC7PwA_JE5Xw",
      "name": "William Jon Salon & Spa",
      "neighborhood": "Regent",
      "address": "2701 University Ave",
      "city": "Ste H",
      "state": "Madison",
      "postal_code": "WI",
      "latitude": 53705,
      "longitude": 43.0731452,
      "stars": -89.4344018,
      "review_count": 4.5,
      "is_open": 14,
      "categories": 1
    },
    {
      "business_id": "DPQnTnNw2PJj7DdENM98Cw",
      "name": "Star Nursery",
      "neighborhood": "5340 Boulder Hwy",
      "address": "Las Vegas",
      "city": "NV",
      "state": 89122,
      "postal_code": 36.105196,
      "latitude": -115.0568796,
      "longitude": 3.5,
      "stars": 25,
      "review_count": 1,
      "is_open": "Nurseries & Gardening;Home & Garden;Shopping",
      "categories": ""
    },
    {
      "business_id": "_F3AMoo_zdl-he384ISQbw",
      "name": "Rock of Ages",
      "neighborhood": "3700 W Flamingo Rd",
      "address": "Las Vegas",
      "city": "NV",
      "state": 89109,
      "postal_code": 36.1169648,
      "latitude": -115.185696,
      "longitude": 4,
      "stars": 213,
      "review_count": 1,
      "is_open": "Arts & Entertainment;Performing Arts",
      "categories": ""
    },
    {
      "business_id": "-ooEO2YqDQVYNHnSF2BPfw",
      "name": "Restaurant Lucca",
      "neighborhood": "Rosemont-La Petite-Patrie",
      "address": "12 Rue Dante",
      "city": "Montréal",
      "state": "QC",
      "postal_code": "H2S 1J5",
      "latitude": 45.5328965,
      "longitude": -73.6136037,
      "stars": 4.5,
      "review_count": 11,
      "is_open": 1,
      "categories": "Italian;Restaurants"
    },
    {
      "business_id": "FmGZh8ZwEnSO860_2eiYHw",
      "name": "Enterprise Rent-A-Car",
      "neighborhood": "Homestead",
      "address": "908 E 8th Ave",
      "city": "Homestead",
      "state": "PA",
      "postal_code": 15120,
      "latitude": 40.409116,
      "longitude": -79.897415,
      "stars": 3,
      "review_count": 4,
      "is_open": 1,
      "categories": "Hotels & Travel;Car Rental"
    },
    {
      "business_id": "Pd52CjgyEU3Rb8co6QfTPw",
      "name": "Flight Deck Bar & Grill",
      "neighborhood": "Southeast",
      "address": "6730 S Las Vegas Blvd",
      "city": "Las Vegas",
      "state": "NV",
      "postal_code": 89119,
      "latitude": 36.0669136,
      "longitude": -115.1708484,
      "stars": 4,
      "review_count": 13,
      "is_open": 1,
      "categories": "Nightlife;Bars;Barbeque;Sports Bars;American (New);Restaurants"
    },
    {
      "business_id": "4srfPk1s8nlm1YusyDUbjg",
      "name": "Subway",
      "neighborhood": "Southeast",
      "address": "6889 S Eastern Ave",
      "city": "Ste 101",
      "state": "Las Vegas",
      "postal_code": "NV",
      "latitude": 89119,
      "longitude": 36.0646523,
      "stars": -115.1189541,
      "review_count": 2.5,
      "is_open": 6,
      "categories": 1
    },
    {
      "business_id": "n7V4cD-KqqE3OXk0irJTyA",
      "name": "GameWorks",
      "neighborhood": "Southeast",
      "address": "6587 Las Vegas Blvd S",
      "city": "Ste 171",
      "state": "Las Vegas",
      "postal_code": "NV",
      "latitude": 89119,
      "longitude": 36.0682585154,
      "stars": -115.1788768,
      "review_count": 3,
      "is_open": 349,
      "categories": 1
    },
    {
      "business_id": "c_XbaJqhm-5ycSBOkVUBmg",
      "name": "Don Taco",
      "neighborhood": "Ville-Marie",
      "address": "1855 Rue Saint Catherine Ouest",
      "city": "H3H 1M2",
      "state": "Montreal",
      "postal_code": "QC",
      "latitude": "H3H 1M2",
      "longitude": 45.4932164,
      "stars": -73.5803794,
      "review_count": 3.5,
      "is_open": 33,
      "categories": 1
    },
    {
      "business_id": "ykJM7EuGziATZ5u2qIT08g",
      "name": "My Fitness World",
      "neighborhood": "South End",
      "address": "1225 S Church St",
      "city": "Ste B",
      "state": "Charlotte",
      "postal_code": "NC",
      "latitude": 28203,
      "longitude": 35.220211,
      "stars": -80.855785,
      "review_count": 5,
      "is_open": 4,
      "categories": 1
    },
    {
      "business_id": "spDZkD6cp0JUUm6ghIWHzA",
      "name": "Kitchen M",
      "neighborhood": "Unionville",
      "address": "8515 McCowan Road",
      "city": "Markham",
      "state": "ON",
      "postal_code": "L3P 5E5",
      "latitude": 43.867918,
      "longitude": -79.2836865,
      "stars": 3,
      "review_count": 80,
      "is_open": 1,
      "categories": "Restaurants;Chinese"
    },
    {
      "business_id": "PEKloTo1IkW_gyxp15e8Dg",
      "name": "Amy's Lash & Beauty Spa",
      "neighborhood": "Summer Hill",
      "address": "1219 Yonge Street",
      "city": "Toronto",
      "state": "ON",
      "postal_code": "M4T 1W4",
      "latitude": 43.6832129897,
      "longitude": -79.3919422965,
      "stars": 3.5,
      "review_count": 7,
      "is_open": 1,
      "categories": "Eyelash Service;Beauty & Spas"
    },
    {
      "business_id": "Sx0C2RsDgrG3RxBBUoBqTw",
      "name": "Kool Radiator Service",
      "neighborhood": "Westside",
      "address": "3228 Meade Ave",
      "city": "Las Vegas",
      "state": "NV",
      "postal_code": 89102,
      "latitude": 36.1366387,
      "longitude": -115.1845851,
      "stars": 3.5,
      "review_count": 9,
      "is_open": 1,
      "categories": "Automotive;Auto Repair"
    },
    {
      "business_id": "v2GJWvZqEAjUc22hZUYzYw",
      "name": "John Armond Actor's Studio",
      "neighborhood": "Westside",
      "address": "8125 W Sahara Ave",
      "city": "Ste 210",
      "state": "Las Vegas",
      "postal_code": "NV",
      "latitude": 89117,
      "longitude": 36.142544,
      "stars": -115.2687306,
      "review_count": 4.5,
      "is_open": 12,
      "categories": 1
    },
    {
      "business_id": "MmR06_kNAbmOPK-0pKvGtA",
      "name": "Cinnabon",
      "neighborhood": "Westside",
      "address": "4300 Meadows Ln",
      "city": "Las Vegas",
      "state": "NV",
      "postal_code": 89107,
      "latitude": 36.1725319,
      "longitude": -115.197258,
      "stars": 4,
      "review_count": 3,
      "is_open": 1,
      "categories": "Food;Coffee & Tea;Desserts"
    },
    {
      "business_id": "ORUUPE_Ahrcop9K7h6rvVQ",
      "name": "Falls Auto Body",
      "neighborhood": "20 W Steels Corners Rd",
      "address": "Cuyahoga Falls",
      "city": "OH",
      "state": 44223,
      "postal_code": 41.1804849,
      "latitude": -81.5094524,
      "longitude": 5,
      "stars": 3,
      "review_count": 1,
      "is_open": "Automotive;Body Shops;Auto Glass Services",
      "categories": ""
    },
    {
      "business_id": "r6Jw8oRCeumxu7Y1WRxT7A",
      "name": "D&D Cleaning",
      "neighborhood": "Urbana",
      "address": "IL",
      "city": 61802,
      "state": 40.1105875,
      "postal_code": -88.2072697,
      "latitude": 5,
      "longitude": 4,
      "stars": 0,
      "review_count": "Home Cleaning;Home Services;Window Washing",
      "is_open": "",
      "categories": ""
    },
    {
      "business_id": "EJFdWX908N8Yc2XG0Lky8A",
      "name": "River Moon Cafe",
      "neighborhood": "Lawrenceville",
      "address": "104 43rd St",
      "city": "Pittsburgh",
      "state": "PA",
      "postal_code": 15201,
      "latitude": 40.472735,
      "longitude": -79.9632647,
      "stars": 4,
      "review_count": 5,
      "is_open": 0,
      "categories": "Cafes;Restaurants"
    },
    {
      "business_id": "LL01hTt_eVdp-ws4zMDsrw",
      "name": "Pil Son",
      "neighborhood": "Financial District",
      "address": "Toronto-Dominion Centre Bank Tower",
      "city": "66 Wellington St W",
      "state": "Ste 2709",
      "postal_code": "Toronto",
      "latitude": "ON",
      "longitude": "M5K 1H1",
      "stars": 43.646954,
      "review_count": -79.382159,
      "is_open": 5,
      "categories": 3
    },
    {
      "business_id": "d6ngz4WmMaQL8Xdfur7bwQ",
      "name": "Crazy Kleen Carpet Cleaning",
      "neighborhood": "15825 W Redfield Rd",
      "address": "Surprise",
      "city": "AZ",
      "state": 85379,
      "postal_code": 33.640227,
      "latitude": -112.3957,
      "longitude": 4.5,
      "stars": 5,
      "review_count": 1,
      "is_open": "Office Cleaning;Carpet Cleaning;Professional Services;Home Cleaning;Home Services;Local Services",
      "categories": ""
    },
    {
      "business_id": "6aFAEeJ3nS-iWGt7Tn7S0Q",
      "name": "KS Audio Video",
      "neighborhood": "19925 Jetton Rd",
      "address": "Ste 100",
      "city": "Cornelius",
      "state": "NC",
      "postal_code": 28031,
      "latitude": 35.4802886,
      "longitude": -80.8857059,
      "stars": 5,
      "review_count": 5,
      "is_open": 1,
      "categories": "Home Services;Television Service Providers;Home Automation;Home Theatre Installation;Professional Services"
    },
    {
      "business_id": "F31RycVVooeIOp9jsXmg6g",
      "name": "The Bluebird Cafe",
      "neighborhood": "Cannonmills",
      "address": "5 Canonmills",
      "city": "Edinburgh",
      "state": "MLN",
      "postal_code": "EH3 5HA",
      "latitude": 55.9624442,
      "longitude": -3.1976623,
      "stars": 4.5,
      "review_count": 16,
      "is_open": 1,
      "categories": "Breakfast & Brunch;Diners;Restaurants;Cafes;British"
    },
    {
      "business_id": "0lCpaZpmjCFEmtti9O9ZdQ",
      "name": "LaPuma Bakery",
      "neighborhood": "12656 Chillicothe Rd",
      "address": "Chesterland",
      "city": "OH",
      "state": 44026,
      "postal_code": 41.5242686,
      "latitude": -81.3379626,
      "longitude": 3.5,
      "stars": 3,
      "review_count": 0,
      "is_open": "Bakeries;Food",
      "categories": ""
    },
    {
      "business_id": "2pD9wZWXDNsZf_MXd8rQtg",
      "name": "Carle Clinic Association",
      "neighborhood": "602 W University Ave",
      "address": "Urbana",
      "city": "IL",
      "state": 61801,
      "postal_code": 40.116627,
      "latitude": -88.2147631,
      "longitude": 2.5,
      "stars": 6,
      "review_count": 1,
      "is_open": "Doctors;Health & Medical",
      "categories": ""
    },
    {
      "business_id": "c6Shr51XcbvAeXp6hb_Exg",
      "name": "Christopher Huston",
      "neighborhood": "MD - TOCA",
      "address": "2222 E Highland Ave",
      "city": "Ste 300",
      "state": "Phoenix",
      "postal_code": "AZ",
      "latitude": 85016,
      "longitude": 33.5063676,
      "stars": -112.0335679,
      "review_count": 2,
      "is_open": 18,
      "categories": 1
    },
    {
      "business_id": "iPa__LOhse-hobC2Xmp-Kw",
      "name": "McDonald's",
      "neighborhood": "1635 E Camelback Rd",
      "address": "Phoenix",
      "city": "AZ",
      "state": 85016,
      "postal_code": 33.5087649,
      "latitude": -112.04624,
      "longitude": 3,
      "stars": 34,
      "review_count": 1,
      "is_open": "Restaurants;Burgers;Fast Food",
      "categories": ""
    },
    {
      "business_id": "XPZT3zLrkLkFSkBVxSsM3w",
      "name": "Sports Authority",
      "neighborhood": "7000 E  Mayo Blvd Building 15",
      "address": "Phoenix",
      "city": "AZ",
      "state": 85054,
      "postal_code": 33.6569065,
      "latitude": -111.9298903,
      "longitude": 2.5,
      "stars": 21,
      "review_count": 0,
      "is_open": "Sporting Goods;Shopping",
      "categories": ""
    },
    {
      "business_id": "zWb-kwaANIPMS_AFBbVOew",
      "name": "Banana Republic",
      "neighborhood": "32 W Towne Mall",
      "address": "Madison",
      "city": "WI",
      "state": 53719,
      "postal_code": 43.0570896,
      "latitude": -89.5092997,
      "longitude": 2,
      "stars": 8,
      "review_count": 1,
      "is_open": "Men's Clothing;Women's Clothing;Fashion;Shopping",
      "categories": ""
    },
    {
      "business_id": "o1fTwfqN0sDFNpV1CkOPPg",
      "name": "Crazy Mocha Coffee",
      "neighborhood": "Lawrenceville",
      "address": "4032 Butler St",
      "city": "Pittsburgh",
      "state": "PA",
      "postal_code": 15201,
      "latitude": 40.4692949,
      "longitude": -79.9612733,
      "stars": 3.5,
      "review_count": 16,
      "is_open": 1,
      "categories": "Restaurants;Sandwiches;Coffee & Tea;Food"
    },
    {
      "business_id": "-nHkhiuerqmfBG3v2v9O-g",
      "name": "Bruegger's Bagels",
      "neighborhood": "5217 Clairton Blvd",
      "address": "Pittsburgh",
      "city": "PA",
      "state": 15236,
      "postal_code": 40.3441937,
      "latitude": -79.970963,
      "longitude": 2.5,
      "stars": 5,
      "review_count": 1,
      "is_open": "Breakfast & Brunch;Bagels;Restaurants;Bakeries;Sandwiches;Food",
      "categories": ""
    },
    {
      "business_id": "NFTh6mj3X2AnHJCKIFUk5Q",
      "name": "Fairfield Inn & Suites",
      "neighborhood": "8540 E Independence Blvd",
      "address": "Charlotte",
      "city": "NC",
      "state": 28105,
      "postal_code": 35.147422,
      "latitude": -80.726487,
      "longitude": 4,
      "stars": 17,
      "review_count": 1,
      "is_open": "Hotels;Event Planning & Services;Hotels & Travel",
      "categories": ""
    },
    {
      "business_id": "EfYExaDrwhj0k611u5lYMg",
      "name": "G G & D Motor Vehicle Services",
      "neighborhood": "4307 W Glendale Ave",
      "address": "Glendale",
      "city": "AZ",
      "state": 85301,
      "postal_code": 33.5369186,
      "latitude": -112.1522269,
      "longitude": 2,
      "stars": 12,
      "review_count": 1,
      "is_open": "Shopping;Public Services & Government;Departments of Motor Vehicles",
      "categories": ""
    },
    {
      "business_id": "AZUCA3oiGou2wLnAYG1P6g",
      "name": "Emergency Chiropractic",
      "neighborhood": "2030 S Rural Rd",
      "address": "Tempe",
      "city": "AZ",
      "state": 85282,
      "postal_code": 33.4062365,
      "latitude": -111.9266226,
      "longitude": 2.5,
      "stars": 3,
      "review_count": 1,
      "is_open": "Health & Medical;Chiropractors",
      "categories": ""
    },
    {
      "business_id": "kKx8iCJkomVQBdWHnmmOiA",
      "name": "Little Caesars Pizza",
      "neighborhood": "10720 E Southern Ave",
      "address": "Mesa",
      "city": "AZ",
      "state": 85209,
      "postal_code": 33.3948766,
      "latitude": -111.6001938,
      "longitude": 2.5,
      "stars": 4,
      "review_count": 1,
      "is_open": "Restaurants;Pizza",
      "categories": ""
    },
    {
      "business_id": "B5EZlEDH6AVDk8tQGHAGqg",
      "name": "Villa Tap",
      "neighborhood": "Sherman",
      "address": "2302 Packers Ave",
      "city": "Madison",
      "state": "WI",
      "postal_code": 53704,
      "latitude": 43.1233893,
      "longitude": -89.3553901,
      "stars": 4,
      "review_count": 34,
      "is_open": 1,
      "categories": "American (Traditional);Nightlife;Dive Bars;Restaurants;Bars"
    },
    {
      "business_id": "bOOgAB_CEWWsxalAthnRSw",
      "name": "Tenors of Rock",
      "neighborhood": "The Strip",
      "address": "3475 S Las Vegas Blvd",
      "city": "Las Vegas",
      "state": "NV",
      "postal_code": 89109,
      "latitude": 36.1193098,
      "longitude": -115.1717702,
      "stars": 4.5,
      "review_count": 46,
      "is_open": 1,
      "categories": "Performing Arts;Arts & Entertainment"
    },
    {
      "business_id": "l5ijDMpYdyKbF0CxiCVO_Q",
      "name": "Starlight Tattoo",
      "neighborhood": "The Strip",
      "address": "3400 Las Vegas Blvd",
      "city": "Las Vegas",
      "state": "NV",
      "postal_code": 89109,
      "latitude": 36.1213295255,
      "longitude": -115.175283886,
      "stars": 4,
      "review_count": 24,
      "is_open": 1,
      "categories": "Beauty & Spas;Piercing;Tattoo"
    },
    {
      "business_id": "nJ3mXjItS8WcwhYbzbfDQw",
      "name": "Scott's Karat Patch",
      "neighborhood": "South Park",
      "address": "5110 Park Rd",
      "city": "Ste 2F",
      "state": "Charlotte",
      "postal_code": "NC",
      "latitude": 28209,
      "longitude": 35.1608893,
      "stars": -80.8492598,
      "review_count": 4,
      "is_open": 5,
      "categories": 1
    },
    {
      "business_id": "NoxzrJbWS4xD9ft0ygD3JA",
      "name": "The Brink Lounge",
      "neighborhood": "Williamson - Marquette",
      "address": "701 E Washington Ave",
      "city": "Ste 105",
      "state": "Madison",
      "postal_code": "WI",
      "latitude": 53703,
      "longitude": 43.0798171,
      "stars": -89.3762962,
      "review_count": 3.5,
      "is_open": 30,
      "categories": 1
    },
    {
      "business_id": "VXH7zXcZzXlmAVN8GSjGRQ",
      "name": "Thai Express",
      "neighborhood": "4700 Keele Street",
      "address": "Toronto",
      "city": "ON",
      "state": "M3J 1P3",
      "postal_code": 43.7748776774,
      "latitude": -79.4946187281,
      "longitude": 3,
      "stars": 5,
      "review_count": 1,
      "is_open": "Imported Food;Specialty Food;Thai;Ethnic Food;Food;Restaurants",
      "categories": ""
    },
    {
      "business_id": "8XQmnE-v6RrsHiqEz6QXdg",
      "name": "Havel's Flowers & Greenhouses",
      "neighborhood": "9294 Mentor Ave",
      "address": "Mentor",
      "city": "OH",
      "state": 44060,
      "postal_code": 41.6777682,
      "latitude": -81.3068638,
      "longitude": 3.5,
      "stars": 4,
      "review_count": 1,
      "is_open": "Florists;Wholesale Stores;Shopping;Flowers & Gifts",
      "categories": ""
    },
    {
      "business_id": "YhV93k9uiMdr3FlV4FHjwA",
      "name": "Caviness Studio",
      "neighborhood": "Phoenix",
      "address": "AZ",
      "city": 85001,
      "state": 33.4499672,
      "postal_code": -112.0702225,
      "latitude": 5,
      "longitude": 4,
      "stars": 1,
      "review_count": "Marketing;Men's Clothing;Restaurants;Graphic Design;Women's Clothing;Screen Printing;Advertising;Pizza;Shopping;Web Design;Fashion;Local Services;Screen Printing/T-Shirt Printing;Professional Services",
      "is_open": "",
      "categories": ""
    },
    {
      "business_id": "w5WBrukfSuEyTjYUYlV4Ug",
      "name": "International Exposition Center",
      "neighborhood": "Riverside",
      "address": "1 I-X Center Dr",
      "city": "Cleveland",
      "state": "OH",
      "postal_code": 44135,
      "latitude": 41.3985053,
      "longitude": -81.8532205,
      "stars": 4,
      "review_count": 16,
      "is_open": 1,
      "categories": "Venues & Event Spaces;Event Planning & Services"
    },
    {
      "business_id": "aFBCmJUYrPeol_P75QX7Jw",
      "name": "Fraticelli's Authentic Italian Grill",
      "neighborhood": "10 Vogell Road",
      "address": "Richmond Hill",
      "city": "ON",
      "state": "L4B 3K4",
      "postal_code": 43.8643333797,
      "latitude": -79.3824108582,
      "longitude": 3,
      "stars": 88,
      "review_count": 1,
      "is_open": "Restaurants;Italian",
      "categories": ""
    },
    {
      "business_id": "F0fEKpTk7gAmuSFI0KW1eQ",
      "name": "Cafe Mastrioni",
      "neighborhood": "Spring Valley",
      "address": "4250 S Rainbow Blvd",
      "city": "Ste 1007",
      "state": "Las Vegas",
      "postal_code": "NV",
      "latitude": 89103,
      "longitude": 36.1110572,
      "stars": -115.2416881,
      "review_count": 1.5,
      "is_open": 3,
      "categories": 0
    },
    {
      "business_id": "dA7KJReGl9PMi3Tg_mBHuw",
      "name": "Poty Group",
      "neighborhood": "Mesa",
      "address": "AZ",
      "city": 85207,
      "state": 33.459458,
      "postal_code": -111.642224,
      "latitude": 5,
      "longitude": 3,
      "stars": 1,
      "review_count": "Real Estate Agents;Home Services;Real Estate",
      "is_open": "",
      "categories": ""
    },
    {
      "business_id": "GX83LORhO99mdNFz9_cZdQ",
      "name": "Dayton Family Medicine",
      "neighborhood": "6840 E Brown Rd",
      "address": "Mesa",
      "city": "AZ",
      "state": 85207,
      "postal_code": 33.437983,
      "latitude": -111.682477,
      "longitude": 2.5,
      "stars": 3,
      "review_count": 1,
      "is_open": "Optometrists;Doctors;Internal Medicine;Health & Medical",
      "categories": ""
    },
    {
      "business_id": "YvxQOMstU2MVDr2uNHs_vw",
      "name": "Mitchell's Ice Cream - Solon Shop",
      "neighborhood": "6130 Kruse Dr",
      "address": "Solon",
      "city": "OH",
      "state": 44139,
      "postal_code": 41.392049,
      "latitude": -81.4426351,
      "longitude": 4.5,
      "stars": 42,
      "review_count": 1,
      "is_open": "Ice Cream & Frozen Yogurt;Food",
      "categories": ""
    },
    {
      "business_id": "NVaM_cKKJT3WWyP21PANzw",
      "name": "City of Mesa Cemetary",
      "neighborhood": "1212 N Center St",
      "address": "Mesa",
      "city": "AZ",
      "state": 85201,
      "postal_code": 33.438755,
      "latitude": -111.832382,
      "longitude": 4.5,
      "stars": 3,
      "review_count": 1,
      "is_open": "Religious Organizations",
      "categories": ""
    },
    {
      "business_id": "dTWfATVrBfKj7Vdn0qWVWg",
      "name": "Flavor Cuisine",
      "neighborhood": "Scarborough",
      "address": "8 Glen Watford Drive",
      "city": "Toronto",
      "state": "ON",
      "postal_code": "M1S 2C1",
      "latitude": 43.7870613,
      "longitude": -79.2761657,
      "stars": 3,
      "review_count": 6,
      "is_open": 1,
      "categories": "Restaurants;Chinese;Food Court"
    },
    {
      "business_id": "HAX1zec191t7QkT2sBZ76A",
      "name": "La Isla Cuban Restaurant",
      "neighborhood": "1816 Galerea Blvd",
      "address": "Ste D",
      "city": "Charlotte",
      "state": "NC",
      "postal_code": 28270,
      "latitude": 35.137223,
      "longitude": -80.734594,
      "stars": 3,
      "review_count": 4,
      "is_open": 0,
      "categories": "Restaurants;Cuban"
    },
    {
      "business_id": "HcEJ2YiSLX_mT3RE0hvKWQ",
      "name": "Blush",
      "neighborhood": "Downtown",
      "address": "135 9th St",
      "city": "Pittsburgh",
      "state": "PA",
      "postal_code": 15222,
      "latitude": 40.444236,
      "longitude": -79.998325,
      "stars": 3,
      "review_count": 21,
      "is_open": 1,
      "categories": "Nightlife;Adult Entertainment;Strip Clubs"
    },
    {
      "business_id": "VZ37HCZVruFm-w_Mkl1aEQ",
      "name": "Conservatory of Dance",
      "neighborhood": "13637 N Tatum Blvd",
      "address": "Ste 8",
      "city": "Phoenix",
      "state": "AZ",
      "postal_code": 85032,
      "latitude": 33.6102929,
      "longitude": -111.9765967,
      "stars": 5,
      "review_count": 16,
      "is_open": 1,
      "categories": "Education;Dance Schools;Arts & Entertainment;Fitness & Instruction;Specialty Schools;Active Life;Dance Studios;Performing Arts"
    },
    {
      "business_id": "zdC6e26U7tS1XtWcJPKCcA",
      "name": "Concord Parkway Animal Hospital",
      "neighborhood": "308 Concord Pkwy N",
      "address": "Concord",
      "city": "NC",
      "state": 28027,
      "postal_code": 35.4038438,
      "latitude": -80.6090928,
      "longitude": 3,
      "stars": 3,
      "review_count": 1,
      "is_open": "Pets;Veterinarians",
      "categories": ""
    },
    {
      "business_id": "VdlPZg2NAu8t8GkdbPLecg",
      "name": "Tandoori Times Indian Bistro",
      "neighborhood": "8140 N Hayden Rd",
      "address": "Ste H115",
      "city": "Scottsdale",
      "state": "AZ",
      "postal_code": 85258,
      "latitude": 33.5552118623,
      "longitude": -111.900456296,
      "stars": 3.5,
      "review_count": 263,
      "is_open": 1,
      "categories": "Restaurants;Gluten-Free;Indian;Seafood"
    },
    {
      "business_id": "c6Q3HP4cmWZbD9GX8kr4IA",
      "name": "Pep Boys",
      "neighborhood": "4837 N Tryon St",
      "address": "Charlotte",
      "city": "NC",
      "state": 28213,
      "postal_code": 35.258682,
      "latitude": -80.785106,
      "longitude": 3.5,
      "stars": 8,
      "review_count": 1,
      "is_open": "Auto Parts & Supplies;Auto Repair;Tires;Automotive",
      "categories": ""
    },
    {
      "business_id": "c7X2SdKxVJMaOnFROO8WEg",
      "name": "Finga Lickin' Caribbean Eatery",
      "neighborhood": "2838 The Plz",
      "address": "Charlotte",
      "city": "NC",
      "state": 28205,
      "postal_code": 35.236823,
      "latitude": -80.801084,
      "longitude": 4.5,
      "stars": 21,
      "review_count": 1,
      "is_open": "Pizza;Food;Internet Cafes;Restaurants;Caribbean",
      "categories": ""
    },
    {
      "business_id": "1nhf9BPXOBFBkbRkpsFaxA",
      "name": "Mirage Grill & Lounge",
      "neighborhood": "Yonge and Eglinton",
      "address": "117 Eglinton Avenue E",
      "city": "Toronto",
      "state": "ON",
      "postal_code": "M4P 1H4",
      "latitude": 43.7074649,
      "longitude": -79.3942852,
      "stars": 2,
      "review_count": 6,
      "is_open": 0,
      "categories": "Breakfast & Brunch;Food;Coffee & Tea;Canadian (New);Restaurants"
    },
    {
      "business_id": "strJsTvTHqWS18GVJQEHoA",
      "name": "Synergy Physical Therapy",
      "neighborhood": "1710 W Horizon Ridge Pkwy",
      "address": "Ste 110",
      "city": "Henderson",
      "state": "NV",
      "postal_code": 89012,
      "latitude": 36.0125267,
      "longitude": -115.0637507,
      "stars": 5,
      "review_count": 22,
      "is_open": 1,
      "categories": "Weight Loss Centers;Physical Therapy;Health & Medical"
    },
    {
      "business_id": "e3rNvRnupvSMu6BABlDUuQ",
      "name": "Henderson Pet Resort",
      "neighborhood": "1450 W Horizon Ridge Pkwy",
      "address": "Ste 425",
      "city": "Henderson",
      "state": "NV",
      "postal_code": 89012,
      "latitude": 36.0223003284,
      "longitude": -115.050184289,
      "stars": 5,
      "review_count": 68,
      "is_open": 1,
      "categories": "Pet Groomers;Pet Sitting;Pets;Pet Services;Pet Training"
    },
    {
      "business_id": "QkG3KUXwqZBW18A9k1xqCA",
      "name": "Red Lobster",
      "neighborhood": "2810 North 75th Ave",
      "address": "Phoenix",
      "city": "AZ",
      "state": 85035,
      "postal_code": 33.4787353,
      "latitude": -112.2213794,
      "longitude": 2.5,
      "stars": 37,
      "review_count": 1,
      "is_open": "American (Traditional);Restaurants;Seafood",
      "categories": ""
    },
    {
      "business_id": "d2HSFutxpaYsCPglJPRe1Q",
      "name": "Winchell's Donut House",
      "neighborhood": "Westside",
      "address": "4700 Meadows Ln",
      "city": "Las Vegas",
      "state": "NV",
      "postal_code": 89107,
      "latitude": 36.1713127195,
      "longitude": -115.205316257,
      "stars": 4,
      "review_count": 13,
      "is_open": 1,
      "categories": "Food;Donuts"
    },
    {
      "business_id": "shNBn6mTKxZ124yPC_H02Q",
      "name": "T.W.Tile",
      "neighborhood": "248 Tara Dr",
      "address": "Pittsburgh",
      "city": "PA",
      "state": 15236,
      "postal_code": 40.327956,
      "latitude": -79.960479,
      "longitude": 3.5,
      "stars": 3,
      "review_count": 1,
      "is_open": "Kitchen & Bath;Countertop Installation;Home Services;Tiling;Contractors;Shopping;Home & Garden",
      "categories": ""
    },
    {
      "business_id": "ZmMCgM4RCqCXJ0Lswu6yxw",
      "name": "A Professional Appliance Repair",
      "neighborhood": "Las Vegas",
      "address": "NV",
      "city": 89108,
      "state": 36.2030945,
      "postal_code": -115.2244853,
      "latitude": 4.5,
      "longitude": 17,
      "stars": 1,
      "review_count": "Local Services;Appliances & Repair",
      "is_open": "",
      "categories": ""
    }
  ];
}
